"""
Analytical — One-time local setup script.
Run this after filling in the manual credentials.

  cd web-apps/analytical
  python setup.py

What it does:
  1. Generates a JWT_SECRET if not already set
  2. Tries to auto-fill ANTHROPIC_API_KEY from other .env files in the repo
  3. Creates backend/.env (or updates it) with everything it can auto-fill
  4. Prints a checklist of what still needs manual input
  5. Installs Python dependencies
  6. Starts the server for a quick smoke test (Ctrl+C to stop)
"""
import os
import sys
import secrets
import subprocess
from pathlib import Path

BACKEND_DIR = Path(__file__).parent / 'backend'
ENV_FILE    = BACKEND_DIR / '.env'
ENV_EXAMPLE = BACKEND_DIR / '.env.example'
REPO_ROOT   = Path(__file__).parent.parent.parent  # my-project/

BOLD  = '\033[1m'
GREEN = '\033[92m'
RED   = '\033[91m'
CYAN  = '\033[96m'
RESET = '\033[0m'

def hdr(msg):
    print(f'\n{BOLD}{CYAN}── {msg} ──{RESET}')

def ok(msg):
    print(f'  {GREEN}✓{RESET} {msg}')

def warn(msg):
    print(f'  {RED}✗{RESET} {msg}')


# ─── Step 1: Read existing .env or start fresh ────────────────
hdr('Reading .env')

env_vars = {}

# Load example as template
if ENV_EXAMPLE.exists():
    for line in ENV_EXAMPLE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, _, v = line.partition('=')
            env_vars[k.strip()] = v.strip()

# Overlay with whatever is already in .env
if ENV_FILE.exists():
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, _, v = line.partition('=')
            env_vars[k.strip()] = v.strip()
    ok('.env exists — loading current values')
else:
    ok('.env not found — will create it')


# ─── Step 2: Auto-fill what we can ───────────────────────────
hdr('Auto-filling credentials')

# Generate JWT_SECRET if missing
if not env_vars.get('JWT_SECRET') or env_vars['JWT_SECRET'] == 'your-secret-key-here-change-this':
    env_vars['JWT_SECRET'] = secrets.token_hex(32)
    ok(f'JWT_SECRET generated: {env_vars["JWT_SECRET"][:16]}...')
else:
    ok('JWT_SECRET already set')

# Find ANTHROPIC_API_KEY from other .env files in the repo
if not env_vars.get('ANTHROPIC_API_KEY'):
    search_dirs = [
        REPO_ROOT / 'python-scripts' / 'hook-optimizer',
        REPO_ROOT / 'python-scripts' / 'content-researcher',
        REPO_ROOT / 'python-scripts' / 'social-media-analytics',
        REPO_ROOT / 'python-scripts' / 'email-agent',
        REPO_ROOT / 'python-scripts' / 'morning-briefing',
    ]
    for d in search_dirs:
        env_path = d / '.env'
        if env_path.exists():
            for line in env_path.read_text().splitlines():
                if line.startswith('ANTHROPIC_API_KEY='):
                    val = line.split('=', 1)[1].strip()
                    if val:
                        env_vars['ANTHROPIC_API_KEY'] = val
                        ok(f'ANTHROPIC_API_KEY found in {d.name}/.env')
                        break
            if env_vars.get('ANTHROPIC_API_KEY'):
                break

if not env_vars.get('ANTHROPIC_API_KEY'):
    warn('ANTHROPIC_API_KEY not found — fill it in .env manually')


# ─── Step 3: Write .env ───────────────────────────────────────
hdr('Writing backend/.env')

lines = [
    '# Analytical — Backend Environment Variables',
    '# Generated by setup.py — safe to re-run',
    '',
    f'DATABASE_URL={env_vars.get("DATABASE_URL", "")}',
    f'JWT_SECRET={env_vars.get("JWT_SECRET", "")}',
    '',
    f'ANTHROPIC_API_KEY={env_vars.get("ANTHROPIC_API_KEY", "")}',
    '',
    f'YOUTUBE_CLIENT_ID={env_vars.get("YOUTUBE_CLIENT_ID", "")}',
    f'YOUTUBE_CLIENT_SECRET={env_vars.get("YOUTUBE_CLIENT_SECRET", "")}',
    f'YOUTUBE_REDIRECT_URI={env_vars.get("YOUTUBE_REDIRECT_URI", "http://localhost:8000/api/connect/youtube/callback")}',
    '',
    f'TIKTOK_CLIENT_KEY={env_vars.get("TIKTOK_CLIENT_KEY", "")}',
    f'TIKTOK_CLIENT_SECRET={env_vars.get("TIKTOK_CLIENT_SECRET", "")}',
    f'TIKTOK_REDIRECT_URI={env_vars.get("TIKTOK_REDIRECT_URI", "http://localhost:8000/api/connect/tiktok/callback")}',
    '',
    f'STRIPE_SECRET_KEY={env_vars.get("STRIPE_SECRET_KEY", "")}',
    f'STRIPE_WEBHOOK_SECRET={env_vars.get("STRIPE_WEBHOOK_SECRET", "")}',
    f'STRIPE_CREATOR_PRICE_ID={env_vars.get("STRIPE_CREATOR_PRICE_ID", "")}',
    '',
    f'FRONTEND_URL={env_vars.get("FRONTEND_URL", "http://localhost:3000")}',
]

ENV_FILE.write_text('\n'.join(lines) + '\n')
ok(f'Written to {ENV_FILE}')


# ─── Step 4: Checklist — what still needs manual input ────────
hdr('Manual credentials checklist')

REQUIRED = {
    'DATABASE_URL':         'Railway: create PostgreSQL → copy DATABASE_URL',
    'YOUTUBE_CLIENT_ID':    'Google Cloud Console: OAuth 2.0 client ID',
    'YOUTUBE_CLIENT_SECRET':'Google Cloud Console: OAuth 2.0 client secret',
    'ANTHROPIC_API_KEY':    'Anthropic Console: anthropic.com/console',
}

OPTIONAL = {
    'TIKTOK_CLIENT_KEY':    'TikTok Developer Portal (can skip for now)',
    'TIKTOK_CLIENT_SECRET': 'TikTok Developer Portal (can skip for now)',
}

all_good = True
for key, instruction in REQUIRED.items():
    val = env_vars.get(key, '').strip()
    if val:
        ok(f'{key} is set')
    else:
        warn(f'{key} is MISSING → {instruction}')
        all_good = False

print()
for key, instruction in OPTIONAL.items():
    val = env_vars.get(key, '').strip()
    if val:
        ok(f'{key} is set (optional)')
    else:
        print(f'  · {key} not set — {instruction}')


# ─── Step 5: Install dependencies ─────────────────────────────
hdr('Installing Python dependencies')

req_file = BACKEND_DIR / 'requirements.txt'
result = subprocess.run(
    [sys.executable, '-m', 'pip', 'install', '-r', str(req_file), '-q'],
    capture_output=True, text=True
)
if result.returncode == 0:
    ok('All dependencies installed')
else:
    warn('pip install had errors:')
    print(result.stderr[:500])


# ─── Done ─────────────────────────────────────────────────────
hdr('Done')

if all_good:
    print(f'\n{GREEN}{BOLD}All required credentials are set. Ready to run:{RESET}')
    print(f'\n  cd web-apps/analytical/backend')
    print(f'  uvicorn main:app --reload --port 8000\n')
else:
    print(f'\n{RED}{BOLD}Fill in the missing credentials in backend/.env, then re-run setup.py{RESET}')
    print(f'\n  Edit: web-apps/analytical/backend/.env\n')
